/*
------------------------------------------------------------
Project : Family Menu App
Script  : 01_create_core_tables.sql
Purpose : Create the core database tables
Author  : Eliza Vardumyan
Version : 1.0
------------------------------------------------------------
*/

BEGIN;

-- =========================================================
-- 1. Languages
-- One row represents one supported application language.
-- =========================================================

CREATE TABLE languages (
    language_code VARCHAR(5) PRIMARY KEY,
    language_name VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- 2. Product Groups
-- Stores technical product group codes.
-- Display names are stored in the translation table.
-- =========================================================

CREATE TABLE product_groups (
    group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(100) NOT NULL UNIQUE
);


-- =========================================================
-- 3. Product Group Translations
-- Stores product group names in different languages.
-- =========================================================

CREATE TABLE product_group_translations (
    group_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    group_name VARCHAR(100) NOT NULL,

    PRIMARY KEY (group_id, language_code),

    CONSTRAINT fk_product_group_translation_group
        FOREIGN KEY (group_id)
        REFERENCES product_groups(group_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_group_translation_language
        FOREIGN KEY (language_code)
        REFERENCES languages(language_code)
        ON DELETE CASCADE
);


-- =========================================================
-- 4. Units
-- Stores technical unit codes.
-- Examples: kg, g, liter, ml, pcs.
-- =========================================================

CREATE TABLE units (
    unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- 5. Unit Translations
-- Stores unit names in different languages.
-- =========================================================

CREATE TABLE unit_translations (
    unit_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    unit_name VARCHAR(50) NOT NULL,

    PRIMARY KEY (unit_id, language_code),

    CONSTRAINT fk_unit_translation_unit
        FOREIGN KEY (unit_id)
        REFERENCES units(unit_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_unit_translation_language
        FOREIGN KEY (language_code)
        REFERENCES languages(language_code)
        ON DELETE CASCADE
);


-- =========================================================
-- 6. Products
-- One row represents one product.
-- Examples: milk, tomato, shampoo, pet food.
-- =========================================================

CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(150) NOT NULL UNIQUE,
    group_id INTEGER NOT NULL,
    unit_id INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,

    CONSTRAINT chk_product_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT fk_product_group
        FOREIGN KEY (group_id)
        REFERENCES product_groups(group_id),

    CONSTRAINT fk_product_unit
        FOREIGN KEY (unit_id)
        REFERENCES units(unit_id)
);


-- =========================================================
-- 7. Product Translations
-- Stores product names in different languages.
-- =========================================================

CREATE TABLE product_translations (
    product_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    product_name VARCHAR(150) NOT NULL,

    PRIMARY KEY (product_id, language_code),

    CONSTRAINT fk_product_translation_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_translation_language
        FOREIGN KEY (language_code)
        REFERENCES languages(language_code)
        ON DELETE CASCADE
);

COMMIT;