/*
------------------------------------------------------------
Project : Family Menu App
Script  : 02_create_recipe_tables.sql
Purpose : Create recipe, category, tag and product-link tables
Founder : Eliza Vardumyan
Version : 1.0
------------------------------------------------------------
*/

BEGIN;


-- =========================================================
-- 1. Recipe Categories
-- Technical category codes independent of language.
-- Examples: breakfast, lunch, salad, main_course.
-- =========================================================

CREATE TABLE recipe_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(100) NOT NULL UNIQUE
);


-- =========================================================
-- 2. Recipe Category Translations
-- Stores category names in each supported language.
-- =========================================================

CREATE TABLE recipe_category_translations (
    category_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    category_name VARCHAR(100) NOT NULL,

    PRIMARY KEY (category_id, language_code),

    CONSTRAINT uq_recipe_category_name_language
        UNIQUE (language_code, category_name),

    CONSTRAINT fk_recipe_category_translation_category
        FOREIGN KEY (category_id)
        REFERENCES recipe_categories(category_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_category_translation_language
        FOREIGN KEY (language_code)
        REFERENCES languages(language_code)
        ON DELETE CASCADE
);


-- =========================================================
-- 3. Recipes
-- Stores technical recipe information.
-- Recipe names are stored in recipe_translations.
-- base_servings is optional.
-- source_url may contain an Instagram or another source link.
-- =========================================================

CREATE TABLE recipes (
    recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_code VARCHAR(150) NOT NULL UNIQUE,
    base_servings INTEGER,
    source_url TEXT,

    CONSTRAINT chk_recipe_base_servings
        CHECK (base_servings IS NULL OR base_servings > 0)
);


-- =========================================================
-- 4. Recipe Translations
-- Stores recipe names in different languages.
-- Armenian can be added first; English and Russian later.
-- =========================================================

CREATE TABLE recipe_translations (
    recipe_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    recipe_name VARCHAR(200) NOT NULL,

    PRIMARY KEY (recipe_id, language_code),

    CONSTRAINT fk_recipe_translation_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_translation_language
        FOREIGN KEY (language_code)
        REFERENCES languages(language_code)
        ON DELETE CASCADE
);


-- =========================================================
-- 5. Recipe Category Assignments
-- Many-to-many relationship:
-- one recipe can have many categories,
-- and one category can contain many recipes.
-- =========================================================

CREATE TABLE recipe_category_assignments (
    recipe_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,

    PRIMARY KEY (recipe_id, category_id),

    CONSTRAINT fk_recipe_category_assignment_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_category_assignment_category
        FOREIGN KEY (category_id)
        REFERENCES recipe_categories(category_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 6. Recipe Tags
-- Technical tag codes independent of language.
-- Examples: quick, vegetarian, kids, budget_friendly.
-- =========================================================

CREATE TABLE recipe_tags (
    tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_code VARCHAR(100) NOT NULL UNIQUE
);


-- =========================================================
-- 7. Recipe Tag Translations
-- Stores tag names in each supported language.
-- =========================================================

CREATE TABLE recipe_tag_translations (
    tag_id INTEGER NOT NULL,
    language_code VARCHAR(5) NOT NULL,
    tag_name VARCHAR(100) NOT NULL,

    PRIMARY KEY (tag_id, language_code),

    CONSTRAINT uq_recipe_tag_name_language
        UNIQUE (language_code, tag_name),

    CONSTRAINT fk_recipe_tag_translation_tag
        FOREIGN KEY (tag_id)
        REFERENCES recipe_tags(tag_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_tag_translation_language
        FOREIGN KEY (language_code)
        REFERENCES languages(language_code)
        ON DELETE CASCADE
);


-- =========================================================
-- 8. Recipe Tag Assignments
-- Many-to-many relationship between recipes and tags.
-- =========================================================

CREATE TABLE recipe_tag_assignments (
    recipe_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,

    PRIMARY KEY (recipe_id, tag_id),

    CONSTRAINT fk_recipe_tag_assignment_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_tag_assignment_tag
        FOREIGN KEY (tag_id)
        REFERENCES recipe_tags(tag_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 9. Recipe Products
-- Connects recipes with the products they require.
-- Stores the quantity and measurement unit used in each recipe.
-- =========================================================

CREATE TABLE recipe_products (
    recipe_product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    recipe_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    unit_id INTEGER NOT NULL,
    quantity NUMERIC(12,3) NOT NULL,

    CONSTRAINT uq_recipe_product
        UNIQUE (recipe_id, product_id),

    CONSTRAINT chk_recipe_product_quantity
        CHECK (quantity > 0),

    CONSTRAINT fk_recipe_product_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_product_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT fk_recipe_product_unit
        FOREIGN KEY (unit_id)
        REFERENCES units(unit_id)
);
COMMIT;